version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ccap_backend
    volumes:
      - ./backend:/app
      - ./ai_models:/ai_models
      - ./blankdeathcert.jpg:/app/blankdeathcert.jpg
      - ./FlorDeathCert.jpg:/app/FlorDeathCert.jpg
      - ./TexasDeathCert.jpg:/app/TexasDeathCert.jpg
      - ./DeathCert1.webp:/app/DeathCert1.webp
      - ./deathcert2.jpg:/app/deathcert2.jpg
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

# Frontend will run locally with `npm start` during development.
